package it.pagopa.pn.bff.utils;

import it.pagopa.pn.bff.generated.openapi.server.v1.dto.notifications.BffFullNotificationV1;
import it.pagopa.pn.bff.generated.openapi.server.v1.dto.notifications.BffNotificationTimelineResponse;
import it.pagopa.pn.bff.mappers.notifications.NotificationSentTimelineMapper;

public class NotificationTimelineUtility {
    /**
     * Populates the status history of the new timeline response.
     *
     * @param source source notification
     * @param target target response generated by MapStruct
     * @param mapper timeline mapper
     */
    public static void populateNotificationStatusHistory(
            BffFullNotificationV1 source,
            BffNotificationTimelineResponse target,
            NotificationSentTimelineMapper mapper
    ) {
    }
}
