AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

  # DataIndexer params
  SenderDashboardIndexesVersionExpiresAfterDays:
    Type: Number
    Default: 365
    Description: Indexes expiration days.

  RaddStoreRegistryVersionExpiresAfterDays:
    Type: Number
    Default: 365
    Description: Radd Store Registry File Version expiration days.

  RaddStoreRegistryNonCurrentVersion:
    Type: Number
    Default: 5
    Description: Radd Store Registry File non current version

  BffBucketRaddStoreRegistryPrefix:
    Type: String
    Description: Name of s3 bucket for generated csv
    Default: 'radd/store'

Resources:

  PnBffLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-bff'
        LogGroupRetention: !Ref LogRetention
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  # Lambda DataIndexer
  SenderDashboardDataIndexerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/log-group.yaml
      Parameters:
        LogGroupName: !Sub ${ProjectName}-bff-SenderDashboardDataIndexer
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: /aws/lambda

  BffBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-bff-data-${AWS::Region}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersionsForSenderDashboardIndexes
            Status: Enabled
            Prefix: sender-dashboard/indexes/
            NoncurrentVersionExpiration:
              NoncurrentDays: !Ref SenderDashboardIndexesVersionExpiresAfterDays
          - Id: DeleteOldVersionsForRaddStoreRegistry
            Status: Enabled
            Prefix: !Ref BffBucketRaddStoreRegistryPrefix
            NoncurrentVersionExpiration:
              NewerNoncurrentVersions: !Ref RaddStoreRegistryNonCurrentVersion
              NoncurrentDays: !Ref RaddStoreRegistryVersionExpiresAfterDays

  # Lambda RaddStoreRegistry
  RaddStoreRegistryLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/log-group.yaml
      Parameters:
        LogGroupName: !Sub ${ProjectName}-bff-RaddStoreRegistryLambda
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: /aws/lambda

Outputs:
  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnBffLogGroup.Outputs.LogGroupName
  RaddStoreRegistryLambdaName:
    Value: RaddStoreRegistryLambdaLogGroup.Outputs.LogGroupName
  # Lambda exports
  DataIndexerLambdaName:
    Value: SenderDashboardDataIndexerLogGroup.Outputs.LogGroupName
  # Bucket exports
  BffBucketArn:
    Value: !GetAtt BffBucket.Arn
  BffBucketName:
    Value: !Ref BffBucket
  BffBucketRegion:
    Value: !Ref AWS::Region
  BffBucketRaddStoreRegistryPrefix:
    Value: !Ref BffBucketRaddStoreRegistryPrefix