name: "Update dependencies"
description: "Updates the commitId of the dependencies chosen"
inputs:
  token:
    description: GitHub token
    required: true
  ref:
    description: Default branch from witch create the pull request
    required: true

runs:
  using: "node20"
  main: "src/index.js"
