name: 'Update dependencies'
description: 'Updates the commitId of the dependencies chosen'
inputs:
  token:
    description: GitHub token
    required: true
  pn-auth-fleet:
    description: Update pn-auth-fleet dependency?
    required: true
    default: "false"
  pn-commons:
    description: Update pn-commons dependency?
    required: true
    default: "false"
  pn-delivery:
    description: Update pn-delivery dependency?
    required: true
    default: "false"
  pn-apikey-manager:
    description: Update pn-apikey-manager dependency?
    required: true
    default: "false"
  pn-external-registries:
    description: Update pn-external-registries dependency?
    required: true
    default: "false"
  pn-user-attributes:
    description: Update pn-user-attributes dependency?
    required: true
    default: "false"
  pn-downtime-logs:
    description: Update pn-downtime-logs dependency?
    required: true
    default: "false"
  pn-delivery-push:
    description: Update pn-delivery-push dependency?
    required: true
    default: "false"
  pn-mandate:
    description: Update pn-mandate dependency?
    required: true
    default: "false"

runs:
  using: 'node20'
  main: 'src/index.js'