name: Update Microservices Dependencies

on:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          fetch-depth: 0
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Install Packages
        run: cd ./.github/workflows/actions/update-dependencies && npm install
      - name: Update dependencies
        uses: ./.github/workflows/actions/update-dependencies
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'develop'