name: Update Microservices Dependencies

on:
  workflow_dispatch:
    inputs:
      pn-auth-fleet:
        description: Update pn-auth-fleet dependency?
        required: true
        type: boolean
        default: false
      pn-commons:
        description: Update pn-commons dependency?
        required: true
        type: boolean
        default: false
      pn-delivery:
        description: Update pn-delivery dependency?
        required: true
        type: boolean
        default: false
      pn-apikey-manager:
        description: Update pn-apikey-manager dependency?
        required: true
        type: boolean
        default: false
      pn-external-registries:
        description: Update pn-external-registries dependency?
        required: true
        type: boolean
        default: false
      pn-user-attributes:
        description: Update pn-user-attributes dependency?
        required: true
        type: boolean
        default: false
      pn-downtime-logs:
        description: Update pn-downtime-logs dependency?
        required: true
        type: boolean
        default: false
      pn-delivery-push:
        description: Update pn-delivery-push dependency?
        required: true
        type: boolean
        default: false
      pn-mandate:
        description: Update pn-mandate dependency?
        required: true
        type: boolean
        default: false
  push:
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # ref: 'develop'
          fetch-depth: 0
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Get POM version
        id: get_pom_version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
      - name: Install Packages
        run: cd ./.github/workflows/actions/update-dependencies && npm install
      - name: Update dependencies
        uses: ./.github/workflows/actions/update-dependencies
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'develop'
          pom-version: ${{ steps.get_pom_version.outputs.version }}
          # pn-auth-fleet: ${{ inputs.pn-auth-fleet }}
          # pn-commons: ${{ inputs.pn-commons }}
          # pn-delivery: ${{ inputs.pn-delivery }}
          # pn-apikey-manager: ${{ inputs.pn-apikey-manager }}
          # pn-external-registries: ${{ inputs.pn-external-registries }}
          # pn-user-attributes: ${{ inputs.pn-user-attributes }}
          # pn-downtime-logs: ${{ inputs.pn-downtime-logs }}
          # pn-delivery-push: ${{ inputs.pn-delivery-push }}
          # pn-mandate: ${{ inputs.pn-mandate }}
          pn-auth-fleet: false
          pn-commons: false
          pn-delivery: true
          pn-apikey-manager: false
          pn-external-registries: false
          pn-user-attributes: false
          pn-downtime-logs: false
          pn-delivery-push: true
          pn-mandate: false